import { TrendingUp, ArrowRight, Shield, CreditCard, RefreshCw, AlertTriangle, Lock, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

interface TermsPageProps {
  onBack?: () => void;
}

const LAST_UPDATED = 'March 25, 2026';

interface Section {
  id: string;
  icon: React.ReactNode;
  title: string;
  content: React.ReactNode;
}

const SECTIONS: Section[] = [
  {
    id: 'overview',
    icon: <FileText size={16} />,
    title: 'Overview & Acceptance',
    content: (
      <>
        <p>
          These Terms of Use ("Terms") govern your access to and use of Tradinsight, operated by <strong className="text-white">SPARKIN LTD</strong>, a company registered in England and Wales ("we", "us", or "our"). By creating an account or using any part of the Tradinsight platform, you agree to be bound by these Terms.
        </p>
        <p>
          If you do not agree to these Terms, do not use Tradinsight. We reserve the right to update these Terms at any time. Continued use of the platform following any changes constitutes acceptance of the revised Terms.
        </p>
        <p>
          These Terms were last updated on <strong className="text-white">{LAST_UPDATED}</strong>.
        </p>
      </>
    ),
  },
  {
    id: 'disclaimer',
    icon: <AlertTriangle size={16} />,
    title: 'Financial Disclaimer — Please Read Carefully',
    content: (
      <>
        <div className="bg-amber-500/8 border border-amber-500/25 rounded-xl p-4 mb-4">
          <p className="text-amber-300 text-sm font-medium leading-relaxed">
            Tradinsight does not provide financial advice. All signals, analysis, TPI readings, and any other content on this platform are for informational purposes only.
          </p>
        </div>
        <p>
          Nothing on Tradinsight constitutes a personalised investment recommendation, financial advice, or an invitation to buy or sell any financial instrument. The signals generated by our system are the output of a systematic, rules-based methodology — they are not tailored to your individual financial situation, investment objectives, tax position, or risk tolerance.
        </p>
        <p>
          Cryptocurrency markets are highly volatile. The value of any position can decrease as well as increase. You may lose some or all of your capital. <strong className="text-white">Past performance of our strategy does not guarantee future results.</strong>
        </p>
        <p>
          You are solely responsible for all trading decisions you make. Before acting on any signal or information provided by Tradinsight, you should conduct your own research and, where appropriate, seek independent financial advice from a qualified professional.
        </p>
      </>
    ),
  },
  {
    id: 'subscription',
    icon: <CreditCard size={16} />,
    title: 'Subscription & Billing',
    content: (
      <>
        <p>
          Tradinsight offers two tiers of access:
        </p>
        <div className="space-y-3 my-4">
          <div className="bg-[#0F172A] border border-[#1F2937] rounded-xl p-4">
            <p className="text-white text-sm font-semibold mb-1">Free Plan</p>
            <p className="text-gray-400 text-sm">Access to delayed BTC signals (minimum 1-week delay) and historical signal data. No payment required. Free access may be modified or discontinued at our discretion with reasonable notice.</p>
          </div>
          <div className="bg-[#0F172A] border border-[#C69214]/20 rounded-xl p-4">
            <p className="text-[#D4A017] text-sm font-semibold mb-1">Premium Plan — $19.99/month</p>
            <p className="text-gray-400 text-sm">Real-time signal delivery, full TPI breakdown, signal analysis, and all premium features. Billed monthly via Stripe. Your subscription renews automatically on the same day each month until cancelled.</p>
          </div>
        </div>
        <p>
          All payments are processed securely by Stripe. SPARKIN LTD does not store your payment card details. By subscribing, you authorise SPARKIN LTD to charge your payment method on a recurring monthly basis.
        </p>
        <p>
          Prices are displayed in USD. Your bank or card issuer may apply currency conversion fees if your account is in a different currency — this is outside our control.
        </p>
        <p>
          We reserve the right to change subscription pricing with a minimum of 30 days' written notice to existing subscribers. Price changes will not affect your current billing cycle.
        </p>
      </>
    ),
  },
  {
    id: 'cancellation',
    icon: <RefreshCw size={16} />,
    title: 'Cancellation',
    content: (
      <>
        <p>
          You may cancel your Premium subscription at any time. Cancellation takes effect at the end of your current billing period — you will retain full Premium access until that date.
        </p>
        <p>
          To cancel, you can manage your subscription directly through your account settings or by contacting us. We do not charge any cancellation fees.
        </p>
        <p>
          Upon cancellation, your account will revert to the Free Plan automatically. Your signal history and account data are retained.
        </p>
      </>
    ),
  },
  {
    id: 'refunds',
    icon: <Shield size={16} />,
    title: 'Refund Policy',
    content: (
      <>
        <p>
          We offer a <strong className="text-white">7-day refund window</strong> from the date of your first Premium subscription payment, subject to the following conditions:
        </p>
        <div className="space-y-2 my-4">
          {[
            { ok: true,  text: 'Refund requests submitted within 7 days of initial payment are eligible for a full refund.' },
            { ok: true,  text: 'No real-time signals were delivered to your account during the 7-day period.' },
            { ok: false, text: 'Refund requests submitted after 7 days of the initial payment date are not eligible.' },
            { ok: false, text: 'Renewals (monthly charges after the first payment) are non-refundable.' },
            { ok: false, text: 'Refunds are not available if a real-time signal was delivered during the refund window.' },
          ].map((item, i) => (
            <div key={i} className={`flex items-start gap-3 rounded-xl p-3 ${item.ok ? 'bg-emerald-500/5 border border-emerald-500/15' : 'bg-rose-500/5 border border-rose-500/15'}`}>
              <span className={`text-sm shrink-0 mt-0.5 ${item.ok ? 'text-emerald-400' : 'text-rose-400'}`}>{item.ok ? '✓' : '✗'}</span>
              <p className="text-gray-300 text-sm leading-relaxed">{item.text}</p>
            </div>
          ))}
        </div>
        <p>
          To request a refund, contact us at <strong className="text-white">support@tradinsight.net</strong> within the eligible window. Refunds are processed within 5–10 business days and returned to your original payment method.
        </p>
        <p>
          This refund policy does not affect any statutory rights you may have under applicable UK consumer protection law.
        </p>
      </>
    ),
  },
  {
    id: 'liability',
    icon: <Shield size={16} />,
    title: 'Limitation of Liability',
    content: (
      <>
        <p>
          To the fullest extent permitted by applicable law, SPARKIN LTD and its officers, directors, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:
        </p>
        <div className="space-y-1.5 my-4">
          {[
            'Trading decisions made based on signals or information provided by Tradinsight',
            'Financial losses incurred as a result of following or not following any signal',
            'Service interruptions, delays, or technical failures',
            'Inaccuracies in signal data, TPI readings, or any other content',
            'Unauthorised access to your account',
          ].map((item, i) => (
            <div key={i} className="flex items-start gap-2.5 text-sm text-gray-400">
              <span className="text-gray-600 mt-1 shrink-0">—</span>
              {item}
            </div>
          ))}
        </div>
        <p>
          Our total cumulative liability to you for any claims arising from your use of Tradinsight shall not exceed the total subscription fees paid by you in the three months preceding the claim.
        </p>
        <p>
          Nothing in these Terms excludes or limits our liability for death or personal injury caused by our negligence, fraud, or any other liability that cannot be excluded under UK law.
        </p>
      </>
    ),
  },
  {
    id: 'privacy',
    icon: <Lock size={16} />,
    title: 'Privacy & Data',
    content: (
      <>
        <p>
          SPARKIN LTD is committed to protecting your personal data in accordance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.
        </p>
        <p className="font-medium text-white text-sm mt-3 mb-2">What we collect</p>
        <div className="space-y-1.5 mb-4">
          {[
            'Account information: name and email address provided at registration',
            'Survey responses: your answers to the onboarding profile questions',
            'Subscription data: billing history and plan status (payment details are held by Stripe, not us)',
            'Usage data: pages visited and features used, for product improvement purposes',
          ].map((item, i) => (
            <div key={i} className="flex items-start gap-2.5 text-sm text-gray-400">
              <span className="text-cyan-500/60 mt-1 shrink-0">·</span>
              {item}
            </div>
          ))}
        </div>
        <p className="font-medium text-white text-sm mb-2">How we use it</p>
        <p>
          Your data is used solely to provide and improve the Tradinsight service. We do not sell, rent, or share your personal data with third parties for marketing purposes. Survey responses are used to personalise your experience and improve our product.
        </p>
        <p className="font-medium text-white text-sm mt-3 mb-2">Third-party processors</p>
        <p>
          We use Supabase for account and data storage, and Stripe for payment processing. Both are GDPR-compliant processors operating under appropriate data processing agreements.
        </p>
        <p className="font-medium text-white text-sm mt-3 mb-2">Your rights</p>
        <p>
          Under UK GDPR, you have the right to access, rectify, or delete your personal data. To exercise these rights, contact us at <strong className="text-white">support@tradinsight.net</strong>. We will respond within 30 days.
        </p>
        <p>
          You may request account deletion at any time. Upon deletion, your personal data will be permanently removed within 30 days, except where retention is required by law.
        </p>
      </>
    ),
  },
  {
    id: 'governing',
    icon: <FileText size={16} />,
    title: 'Governing Law',
    content: (
      <>
        <p>
          These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </p>
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
        </p>
        <p>
          For any questions regarding these Terms, contact us at <strong className="text-white">support@tradinsight.net</strong>.
        </p>
      </>
    ),
  },
];

export function TermsPage({ onBack }: TermsPageProps) {
  const { user } = useAuth();
  const navigate = useNavigate();

  const handleBack = () => {
    if (onBack) { onBack(); return; }
    if (user) { navigate('/dashboard'); } else { navigate('/'); }
  };
  return (
    <div className="min-h-screen bg-[#0B0F19]">

      {/* Header */}
      <header className="border-b border-[#1F2937] bg-[#0F172A]/80 backdrop-blur sticky top-0 z-40">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <TrendingUp className="text-cyan-400" size={28} />
              <span className="text-xl font-bold text-white tracking-tight">Tradinsight</span>
            </div>
            {onBack && (
              <button
                onClick={handleBack}
                className="flex items-center gap-1.5 text-gray-400 hover:text-white text-sm transition-colors"
              >
                <ArrowRight size={15} className="rotate-180" />
                Back
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-3xl">

        {/* Page header */}
        <div className="mb-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#1F2937] bg-[#121826] px-4 py-1.5 mb-5">
            <FileText size={13} className="text-gray-400" />
            <span className="text-gray-400 text-xs font-semibold tracking-widest uppercase">Legal</span>
          </div>
          <h1 className="text-3xl font-bold text-white tracking-tight mb-3">
            Terms of Use & Policies
          </h1>
          <p className="text-gray-400 text-sm leading-relaxed">
            These terms govern your use of Tradinsight, operated by SPARKIN LTD (registered in England and Wales).
            Last updated: <span className="text-gray-300">{LAST_UPDATED}</span>.
          </p>
        </div>

        {/* Quick nav */}
        <div className="bg-[#121826] border border-[#1F2937] rounded-2xl p-5 mb-8">
          <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-3">Contents</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
            {SECTIONS.map((section) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                className="flex items-center gap-2 text-gray-400 hover:text-cyan-400 text-sm transition-colors py-1"
              >
                <span className="text-gray-600">{section.icon}</span>
                {section.title}
              </a>
            ))}
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {SECTIONS.map((section) => (
            <div key={section.id} id={section.id} className="scroll-mt-20">
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-7 h-7 rounded-lg bg-[#121826] border border-[#1F2937] flex items-center justify-center text-gray-400">
                  {section.icon}
                </div>
                <h2 className="text-lg font-bold text-white tracking-tight">{section.title}</h2>
              </div>
              <div className="bg-[#121826] border border-[#1F2937] rounded-2xl p-6 prose prose-sm prose-invert max-w-none
                [&>p]:text-gray-400 [&>p]:leading-relaxed [&>p]:mb-3 [&>p:last-child]:mb-0
                [&_strong]:font-semibold">
                {section.content}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-10 text-center">
          <p className="text-gray-600 text-xs">
            SPARKIN LTD · Registered in England and Wales · Last updated {LAST_UPDATED}
          </p>
          <p className="text-gray-700 text-xs mt-1">
            Questions? Contact us at support@tradinsight.net
          </p>
        </div>

      </main>
    </div>
  );
}